config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root is quote's index
  root 'quotes#index'

  # we do not use resources because we use only some of CRUD operations
  # for creating
  get '/quotes/new', to: 'quotes#new', as: :new_quote
  post '/quote', to: 'quotes#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ActiveRecord::Base 
    validates :quotation, presence: true, length: { in: 5..255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

    def index
        # some sort of pagination ?
        @quotes = Quote.order(created_at: :desc)
    end

    def new 
        @quote = Quote.new
    end

    def create 
        @quote = Quote.new(quote_params)
        
        if @quote.save 
            redirect_to root_path, notice: 'Quote created!'
        else
            render :new
        end
    end

    private
        # params that are allowed for security
        def quote_params
            params.require(:quote).permit(:quotation)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_msg.erb
<div class="container">
<% if !flash[:notice].blank?  %>
    <div class="alert alert-success" style="text-align: center;">
            <%= flash[:notice] %>
    </div>
<% end %>

app/views/layouts/_navbar.erb
<div class="navbar navbar-default navbar-static-top stick" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <%= link_to 'Sample app', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
                <li><%= link_to 'Quotes', root_path %></li>
                <li><%= link_to 'New quote', new_quote_path %></li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap +/- 3.0 although outdated --> 
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  </head>

  <body>

    <%= render './layouts/navbar' %>
    <%= render './layouts/flash_msg' %>
    <div class="container">
      <%= yield %>
    </div>
    

  </body>
</html>

app/views/quotes/_error_msg.erb
<div class="container">
    <% if @quote.errors.any?%>
    <div class="alert alert-danger">
        <ul>
            <% @quote.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
</div>

app/views/quotes/_form.erb
<%= form_for @quote, url: quote_path(@quote) do |f| %>
    <table class="table table-striped">
        <tr>
            <%= f.label :quotation %>
            <%= f.text_area :quotation, cols: 20, rows: 10, class: 'form-control' %>
        <tr/>
        <tr>
            <%= f.submit 'Save', class: 'form-control btn-success' %>
        </tr>
    </table>
<% end %>

app/views/quotes/index.html.erb
 <div class="container">   
    <h1>Quotations</h1>

    <!-- Using bootstrap +/- 3.7 although it's outdated  - bulma/bootstrap 4 ? --> 
    <table class='table table-sriped'>
            <tr class="info">
                <th>Quotation</th>
                <th>Posted at</th>
            </tr>    

        <% @quotes.each do |quote| %> 
            <tr>
                <td><%= quote.quotation %></td>
                <!-- some 'bad' usage of timestamp ;) -->
                <td><%= localize(quote.created_at, format: :long) %></td>      
            </tr>
        <% end %>
    </table>
</div>

app/views/quotes/new.html.erb
<h1>Create new quote</h1>
<%= render 'error_msg' %>
<%= render 'form' %>